// Auto-generated by scripts/generate-client.ts
// DO NOT EDIT MANUALLY

import {
  ApiClientBase,
  ApiError,
  ValidationError,
  type RequestOptions,
  type ApiClientOptions,
  type SSEOptions,
} from "./base";

// ============================================
// Route Types
// ============================================

export namespace Routes {
  export namespace Users {
    export type GetInput = {
  id: number;
};
    export type GetOutput = {
  id: number;
  name: string;
  email: string;
};

    export type CreateInput = {
  name: string;
  email: string;
};
    export type CreateOutput = {
  id: number;
  name: string;
  email: string;
};

    export type ListInput = {
  page?: number;
  limit?: number;
};
    export type ListOutput = {
  users: {
  id: number;
  name: string;
}[];
  total: number;
};
  }

  export namespace Orders {
    export type CreateInput = {
  items: {
  productId: number;
  quantity: number;
}[];
};
    export type CreateOutput = {
  orderId: string;
  total: number;
};
  }
}

// ============================================
// SSE Event Types
// ============================================

export interface SSEEvents {}

// ============================================
// API Client
// ============================================

export interface ApiClientConfig extends ApiClientOptions {
  /** Base URL of the API server */
  baseUrl: string;
}

/**
 * Typed API Client
 *
 * @example
 * ```ts
 * const api = createApiClient({ baseUrl: "http://localhost:3000" });
 *
 * // Typed route calls
 * const result = await api.users.get({ id: 1 });
 *
 * // SSE events
 * api.connect();
 * api.on("notifications.new", (data) => {
 *   console.log(data.message);
 * });
 * ```
 */
export class ApiClient extends ApiClientBase<SSEEvents> {
  constructor(config: ApiClientConfig) {
    super(config.baseUrl, {
      credentials: "include",
      ...config,
    });
  }

  // ==========================================
  // Route Namespaces
  // ==========================================

  users = {
    get: (input: Routes.Users.GetInput, options?: RequestOptions): Promise<Routes.Users.GetOutput> =>
      this.request("users.get", input, options),

    create: (input: Routes.Users.CreateInput, options?: RequestOptions): Promise<Routes.Users.CreateOutput> =>
      this.request("users.create", input, options),

    list: (input: Routes.Users.ListInput, options?: RequestOptions): Promise<Routes.Users.ListOutput> =>
      this.request("users.list", input, options)
  };

  orders = {
    create: (input: Routes.Orders.CreateInput, options?: RequestOptions): Promise<Routes.Orders.CreateOutput> =>
      this.request("orders.create", input, options),

    status: (init?: RequestInit): Promise<Response> =>
      this.rawRequest("orders.status", init)
  };
}

// ============================================
// Factory Function
// ============================================

/**
 * Create a new API client instance
 *
 * @param config - Client configuration
 * @returns Typed API client
 *
 * @example
 * ```ts
 * const api = createApiClient({ baseUrl: "http://localhost:3000" });
 * const user = await api.users.get({ id: 1 });
 * ```
 */
export function createApiClient(config: ApiClientConfig): ApiClient {
  return new ApiClient(config);
}

// Re-export base types for convenience
export { ApiError, ValidationError, type RequestOptions, type SSEOptions };
