/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface EmailTokens {
  created_at: Generated<string>;
  email: string;
  expires_at: string;
  id: string | null;
  token_hash: string;
  type: string;
  used_at: string | null;
}

export interface DB {
  email_tokens: EmailTokens;
}
