
// Auto-generated by scripts/generate-server.ts
// Do not edit manually.

/// <reference path="./registry.d.ts" />
import type { PluginRegistry, CoreServices } from "./core";
import type { Errors } from "./core/errors";
import type { Kysely } from "kysely";

// Intersection of all plugin schemas - enables db.selectFrom("users"), db.selectFrom("posts"), etc.
type DatabaseSchema = PluginRegistry["auth"]["schema"] & PluginRegistry["counter"]["schema"] & PluginRegistry["stats"]["schema"];

export interface GlobalContext {
  db: Kysely<DatabaseSchema>;
  plugins: {
    [K in keyof PluginRegistry]: PluginRegistry[K]["service"];
  };
  core: CoreServices;
  /** Convenience access to error factories - same as core.errors */
  errors: Errors;
  ip: string;
  requestId?: string;
  user?: any;
}
