// Auto-generated by scripts/generate-registry.ts
import { type Register, type InferService, type InferSchema, type InferHandlers, type InferMiddleware, type InferDependencies } from "./core";
import { authPlugin } from "./plugins/auth";
import { counterPlugin } from "./plugins/counter";
import { statsPlugin } from "./plugins/stats";

declare module "./core" {
  export interface PluginRegistry {
    auth: Register<InferService<typeof authPlugin>, InferSchema<typeof authPlugin>, InferHandlers<typeof authPlugin>, InferDependencies<typeof authPlugin>, InferMiddleware<typeof authPlugin>>;
    counter: Register<InferService<typeof counterPlugin>, InferSchema<typeof counterPlugin>, InferHandlers<typeof counterPlugin>, InferDependencies<typeof counterPlugin>, InferMiddleware<typeof counterPlugin>>;
    stats: Register<InferService<typeof statsPlugin>, InferSchema<typeof statsPlugin>, InferHandlers<typeof statsPlugin>, InferDependencies<typeof statsPlugin>, InferMiddleware<typeof statsPlugin>>;
  }

  export interface PluginHandlerRegistry extends
    // Merge all plugin handlers
    InferHandlers<typeof authPlugin>,
    InferHandlers<typeof counterPlugin>,
    InferHandlers<typeof statsPlugin>
  {}

  export interface PluginMiddlewareRegistry extends
    // Merge all plugin middleware
    InferMiddleware<typeof authPlugin>,
    InferMiddleware<typeof counterPlugin>,
    InferMiddleware<typeof statsPlugin>
  {}
}

// Union type for all available handlers
export type AvailableHandlers = "typed" | "raw";

// Union type for all available middleware
export type AvailableMiddleware = "authRequired";

// Augment IRouteBuilder interface with custom handler methods
declare module "./router" {
  export interface IRouteBuilder<TRouter> {

  }

  export interface IMiddlewareBuilder<TRouter> {
    /** Middleware from authPlugin */
    authRequired(config?: InferMiddleware<typeof authPlugin>["authRequired"]["__config"]): this;
  }
}
