// Auto-generated by scripts/generate-registry.ts
// Runtime registration of custom handler and middleware methods
/// <reference path="./registry.d.ts" />
import { RouteBuilder, MiddlewareBuilder } from "./router";

// Handler registrations


// Middleware registrations
// Register "authRequired" middleware method from authPlugin
(MiddlewareBuilder.prototype as any).authRequired = function(config: any = {}) {
  return this.addMiddleware("authRequired", config);
};
