/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface ResourceGrants {
  created_at: Generated<string>;
  granted_by: string | null;
  grantee_id: string;
  grantee_type: string;
  id: string | null;
  permissions: Generated<string>;
  resource_id: string;
  resource_type: string;
  tenant_id: string;
}

export interface Roles {
  created_at: Generated<string>;
  description: string | null;
  id: string | null;
  inherits_from: string | null;
  is_default: Generated<number>;
  name: string;
  permissions: Generated<string>;
  tenant_id: string | null;
  updated_at: string;
}

export interface TenantMembers {
  created_at: Generated<string>;
  id: string | null;
  tenant_id: string;
  user_id: string;
}

export interface Tenants {
  created_at: Generated<string>;
  id: string | null;
  name: string;
  settings: string | null;
  slug: string;
  updated_at: string;
}

export interface UserRoles {
  assigned_by: string | null;
  created_at: Generated<string>;
  id: string | null;
  role_id: string;
  tenant_id: string;
  user_id: string;
}

export interface DB {
  resource_grants: ResourceGrants;
  roles: Roles;
  tenant_members: TenantMembers;
  tenants: Tenants;
  user_roles: UserRoles;
}
