// Auto-generated by donkeylabs generate
// API Client

import { ApiClientBase, type ApiClientOptions } from "@donkeylabs/server/client";

export class ApiClient extends ApiClientBase<{}> {
  constructor(baseUrl: string, options?: ApiClientOptions) {
    super(baseUrl, options);
  }

  api = {
    health: {
      ping: (input: any) => this.request("api.health.ping", input)
    },
    hello: {
      test: (input: any) => this.request("api.hello.test", input),
      ping: (input: any) => this.request("api.hello.ping", input),
      pong: (input: any) => this.request("api.hello.pong", input)
    }
  };
}

export function createApiClient(baseUrl: string, options?: ApiClientOptions) {
  return new ApiClient(baseUrl, options);
}
