// Auto-generated by donkeylabs generate
// App context - import as: import type { AppContext } from ".@donkeylabs/server/context";

/// <reference path="./registry.d.ts" />
import type { PluginRegistry, CoreServices, Errors } from "@donkeylabs/server";
import type { Kysely } from "kysely";

/** Merged database schema from all plugins */
export type DatabaseSchema = PluginRegistry["stats"]["schema"];

/**
 * Fully typed application context.
 * Use this instead of ServerContext for typed plugin access.
 */
export interface AppContext {
  /** Database with merged schema from all plugins */
  db: Kysely<DatabaseSchema>;
  /** Typed plugin services */
  plugins: {
    [K in keyof PluginRegistry]: PluginRegistry[K]["service"];
  };
  /** Core services (logger, cache, events, etc.) */
  core: Omit<CoreServices, "db" | "config" | "errors">;
  /** Error factories (BadRequest, NotFound, etc.) */
  errors: Errors;
  /** Application config */
  config: Record<string, any>;
  /** Client IP address */
  ip: string;
  /** Unique request ID */
  requestId: string;
  /** Authenticated user (set by auth middleware) */
  user?: any;
}

// Re-export as GlobalContext for backwards compatibility
export type GlobalContext = AppContext;
