// Auto-generated by donkeylabs generate
import { type Register, type InferService, type InferSchema, type InferHandlers, type InferMiddleware, type InferDependencies } from "@donkeylabs/server";
import { statsPlugin } from "/Users/franciscosainzwilliams/Documents/GitHub/server/examples/starter/src/plugins/stats/index";

declare module "@donkeylabs/server" {
  export interface PluginRegistry {
    stats: Register<InferService<typeof statsPlugin>, InferSchema<typeof statsPlugin>, InferHandlers<typeof statsPlugin>, InferDependencies<typeof statsPlugin>, InferMiddleware<typeof statsPlugin>>;
  }

  export interface PluginHandlerRegistry extends
    InferHandlers<typeof statsPlugin>
  {}

  export interface PluginMiddlewareRegistry extends
    InferMiddleware<typeof statsPlugin>
  {}
}

export type AvailableHandlers = "typed" | "raw";
export type AvailableMiddleware = "timing";

declare module "@donkeylabs/server" {
  export interface IRouteBuilder<TRouter> {

  }

  export interface IMiddlewareBuilder<TRouter> {
    /** Middleware from statsPlugin */
    timing(config?: InferMiddleware<typeof statsPlugin>["timing"]["__config"]): TRouter;
  }
}
