// Auto-generated by donkeylabs generate
// Route Input/Output types - import as: import { Health } from ".@donkeylabs/server/routes";

import { z } from "zod";
import type { AppContext } from "./context";
import { Input as Health_Ping_Input, Output as Health_Ping_Output } from "../../src/routes/health/ping/schema";

export namespace Health {
  export namespace Ping {
    /** Zod schema for input validation */
    export const Input = Health_Ping_Input;
    /** Zod schema for output validation */
    export const Output = Health_Ping_Output;
    /** TypeScript type for input data */
    export type Input = z.infer<typeof Health_Ping_Input>;
    /** TypeScript type for output data */
    export type Output = z.infer<typeof Health_Ping_Output>;
  }
  /** Route contract type - use with Route<Health.Ping> and Handler<Health.Ping> */
  export type Ping = { input: Ping.Input; output: Ping.Output };
}
