// Auto-generated by donkeylabs generate
// DO NOT EDIT MANUALLY

import { UnifiedApiClientBase, SSEConnection, type ClientOptions, type RequestOptions, type SSEConnectionOptions } from "@donkeylabs/adapter-sveltekit/client";

// Utility type that forces TypeScript to expand types on hover
type Expand<T> = T extends infer O ? { [K in keyof O]: O[K] } : never;

// ============================================
// Route Types
// ============================================

export namespace Routes {
  // No typed routes found
}

// ============================================
// API Client
// ============================================

export class ApiClient extends UnifiedApiClientBase {
  constructor(options?: ClientOptions) {
    super(options);
  }

  // No routes defined
}

/**
 * Create an API client instance
 *
 * @param options.locals - Pass SvelteKit locals for SSR direct calls (no HTTP overhead)
 * @param options.baseUrl - Override the base URL for HTTP calls
 *
 * @example SSR usage in +page.server.ts:
 * ```ts
 * export const load = async ({ locals }) => {
 *   const api = createApi({ locals });
 *   const data = await api.myRoute.get({}); // Direct call, no HTTP!
 *   return { data };
 * };
 * ```
 *
 * @example Browser usage in +page.svelte:
 * ```svelte
 * <script>
 *   import { createApi } from '$lib/api';
 *   const api = createApi(); // HTTP calls
 *   let data = $state(null);
 *   async function load() {
 *     data = await api.myRoute.get({});
 *   }
 * </script>
 * ```
 */
export function createApi(options?: ClientOptions) {
  return new ApiClient(options);
}
