// Server entry for @donkeylabs/adapter-sveltekit
import { AppServer } from "@donkeylabs/server";
import { Kysely } from "kysely";
import { BunSqliteDialect } from "kysely-bun-sqlite";
import { Database } from "bun:sqlite";
import { demoPlugin } from "./plugins/demo";
import { workflowDemoPlugin } from "./plugins/workflow-demo";
import { authPlugin } from "./plugins/auth";
import { emailPlugin } from "./plugins/email";
import { permissionsPlugin } from "./plugins/permissions";
import demoRoutes from "./routes/demo";
import { exampleRouter } from "./routes/example";
import { authRouter } from "./routes/auth";
import { permissionsRouter } from "./routes/permissions";
import { tenantsRouter } from "./routes/tenants";

// Simple in-memory database
const db = new Kysely<{}>({
  dialect: new BunSqliteDialect({ database: new Database(":memory:") }),
});

// Create server
// Note: Client types are generated by `donkeylabs generate` (via vite plugin or CLI)
export const server = new AppServer({
  db,
  port: 0, // Port managed by adapter
  // Admin dashboard - enabled in dev mode
  admin: {
    enabled: true,
    prefix: "admin",
  },
});

// =============================================================================
// AUTH PLUGIN CONFIGURATION
// =============================================================================
// Choose your auth strategy:
//
// 1. SESSION (default) - Stateful, stores sessions in database
//    Best for: Web apps, server-rendered pages
//    server.registerPlugin(authPlugin());
//
// 2. JWT - Stateless tokens, no database lookup needed
//    Best for: Mobile apps, microservices, APIs
//    server.registerPlugin(authPlugin({
//      strategy: "jwt",
//      jwt: { secret: process.env.JWT_SECRET! },
//    }));
//
// 3. REFRESH-TOKEN - Short-lived access + long-lived refresh token
//    Best for: SPAs, mobile apps needing token refresh
//    server.registerPlugin(authPlugin({
//      strategy: "refresh-token",
//      jwt: {
//        secret: process.env.JWT_SECRET!,
//        accessExpiry: "15m",
//        refreshExpiry: "30d",
//      },
//      cookie: { httpOnly: true, secure: true },
//    }));
//
// =============================================================================

// Using default session strategy for this template
server.registerPlugin(authPlugin({}));

// Email plugin - supports Resend or console (for development)
// Configure with process.env.RESEND_API_KEY for production
server.registerPlugin(emailPlugin({
  provider: process.env.RESEND_API_KEY ? "resend" : "console",
  resend: process.env.RESEND_API_KEY ? { apiKey: process.env.RESEND_API_KEY } : undefined,
  from: process.env.EMAIL_FROM || "noreply@example.com",
  baseUrl: process.env.PUBLIC_BASE_URL || "http://localhost:5173",
}));

// =============================================================================
// PERMISSIONS PLUGIN - Multi-tenant RBAC
// =============================================================================
// Define your app's permissions here for type-safe checking.
// Client can use: api.permissions.check({ permissions: ["documents.create"] })
//
server.registerPlugin(permissionsPlugin({
  permissions: {
    // Documents
    documents: ["create", "read", "write", "delete", "admin"],
    // Members & Roles
    members: ["invite", "remove", "list"],
    roles: ["create", "assign", "manage"],
    // Billing (example)
    billing: ["view", "manage"],
  } as const,
  defaultRoles: [
    {
      name: "Admin",
      permissions: ["*"], // Full access
      isDefault: false,
    },
    {
      name: "Member",
      permissions: [
        "documents.create",
        "documents.read",
        "documents.write",
        "members.list",
      ],
      isDefault: true, // Auto-assigned to new members
    },
    {
      name: "Viewer",
      permissions: ["documents.read", "members.list"],
      isDefault: false,
    },
  ],
}));

server.registerPlugin(demoPlugin);
server.registerPlugin(workflowDemoPlugin);

// Register routes
server.use(authRouter);
server.use(permissionsRouter);
server.use(tenantsRouter);
server.use(demoRoutes);
server.use(exampleRouter);
