// Auto-generated by @donkeylabs/adapter-swift
// DO NOT EDIT MANUALLY

import Foundation

/// API error types returned by the Donkeylabs server
public enum ApiError: Error, LocalizedError, Sendable {
    /// Server error with status code, error code, message, and optional details
    case server(status: Int, code: String, message: String, details: AnyCodable?)

    /// Validation error with field-level issues
    case validation(issues: [ValidationIssue])

    /// Response could not be parsed
    case invalidResponse

    /// Underlying network/transport error
    case networkError(Error)

    /// A single validation issue
    public struct ValidationIssue: Sendable {
        public let path: [String]
        public let message: String

        public init(path: [String], message: String) {
            self.path = path
            self.message = message
        }
    }

    public var errorDescription: String? {
        switch self {
        case .server(let status, let code, let message, _):
            return "[\(status)] \(code): \(message)"
        case .validation(let issues):
            let details = issues.map { "\($0.path.joined(separator: ".")): \($0.message)" }
            return "Validation failed: \(details.joined(separator: "; "))"
        case .invalidResponse:
            return "Invalid response from server"
        case .networkError(let error):
            return "Network error: \(error.localizedDescription)"
        }
    }

    /// HTTP status code if available
    public var statusCode: Int? {
        switch self {
        case .server(let status, _, _, _):
            return status
        case .validation:
            return 400
        default:
            return nil
        }
    }

    /// Error code string if available
    public var code: String? {
        switch self {
        case .server(_, let code, _, _):
            return code
        case .validation:
            return "VALIDATION_ERROR"
        default:
            return nil
        }
    }
}
