// Auto-generated by donkeylabs generate
// DO NOT EDIT MANUALLY

import { UnifiedApiClientBase, type ClientOptions } from "@donkeylabs/adapter-sveltekit/client";

// Utility type that forces TypeScript to expand types on hover
type Expand<T> = T extends infer O ? { [K in keyof O]: O[K] } : never;

// ============================================
// Route Types
// ============================================

export namespace Routes {
  export namespace Counter {
    export type GetInput = Expand<Record<string, never>>;
    export type GetOutput = Expand<{
  count: number;
}>;

    export type IncrementInput = Expand<Record<string, never>>;
    export type IncrementOutput = Expand<{
  count: number;
}>;

    export type DecrementInput = Expand<Record<string, never>>;
    export type DecrementOutput = Expand<{
  count: number;
}>;

    export type ResetInput = Expand<Record<string, never>>;
    export type ResetOutput = Expand<{
  count: number;
}>;
  }

  export namespace Cache {
    export type SetInput = Expand<{
  key: string;
  value: any;
  ttl?: number;
}>;
    export type SetOutput = Expand<{
  success: boolean;
}>;

    export type GetInput = Expand<{
  key: string;
}>;
    export type GetOutput = Expand<{
  value?: any;
  exists: boolean;
}>;

    export type DeleteInput = Expand<{
  key: string;
}>;
    export type DeleteOutput = Expand<{
  success: boolean;
}>;

    export type KeysInput = Expand<Record<string, never>>;
    export type KeysOutput = Expand<{
  keys: string[];
}>;
  }

  export namespace Jobs {
    export type EnqueueInput = Expand<{
  name: string;
  data: unknown;
  delay?: number;
}>;
    export type EnqueueOutput = Expand<{
  jobId: string;
}>;

    export type StatsInput = Expand<Record<string, never>>;
    export type StatsOutput = Expand<{
  pending: number;
  running: number;
  completed: number;
}>;
  }

  export namespace Cron {
    export type ListInput = Expand<Record<string, never>>;
    export type ListOutput = Expand<{
  tasks: {
  id: string;
  name: string;
  expression: string;
  enabled: boolean;
  lastRun?: string;
  nextRun?: string;
}[];
}>;
  }

  export namespace Ratelimit {
    export type CheckInput = Expand<{
  key: string;
  limit: number;
  window: number;
}>;
    export type CheckOutput = Expand<{
  allowed: boolean;
  remaining: number;
  resetAt: Date;
}>;

    export type ResetInput = Expand<{
  key: string;
}>;
    export type ResetOutput = Expand<{
  success: boolean;
}>;
  }

  export namespace Events {
    export type EmitInput = Expand<{
  event: string;
  data: unknown;
}>;
    export type EmitOutput = Expand<{
  success: boolean;
}>;
  }

  export namespace SseRoutes {
    export type BroadcastInput = Expand<{
  channel: string;
  event: string;
  data: any;
}>;
    export type BroadcastOutput = Expand<{
  success: boolean;
  recipients: number;
}>;

    export type ClientsInput = Expand<Record<string, never>>;
    export type ClientsOutput = Expand<{
  total: number;
  byChannel: number;
}>;
  }
}

// ============================================
// API Client
// ============================================

export class ApiClient extends UnifiedApiClientBase {
  constructor(options?: ClientOptions) {
    super(options);
  }

  counter = {
    get: (input: Routes.Counter.GetInput): Promise<Routes.Counter.GetOutput> => this.request("api.counter.get", input),
    increment: (input: Routes.Counter.IncrementInput): Promise<Routes.Counter.IncrementOutput> => this.request("api.counter.increment", input),
    decrement: (input: Routes.Counter.DecrementInput): Promise<Routes.Counter.DecrementOutput> => this.request("api.counter.decrement", input),
    reset: (input: Routes.Counter.ResetInput): Promise<Routes.Counter.ResetOutput> => this.request("api.counter.reset", input)
  };

  cache = {
    set: (input: Routes.Cache.SetInput): Promise<Routes.Cache.SetOutput> => this.request("api.cache.set", input),
    get: (input: Routes.Cache.GetInput): Promise<Routes.Cache.GetOutput> => this.request("api.cache.get", input),
    delete: (input: Routes.Cache.DeleteInput): Promise<Routes.Cache.DeleteOutput> => this.request("api.cache.delete", input),
    keys: (input: Routes.Cache.KeysInput): Promise<Routes.Cache.KeysOutput> => this.request("api.cache.keys", input)
  };

  jobs = {
    enqueue: (input: Routes.Jobs.EnqueueInput): Promise<Routes.Jobs.EnqueueOutput> => this.request("api.jobs.enqueue", input),
    stats: (input: Routes.Jobs.StatsInput): Promise<Routes.Jobs.StatsOutput> => this.request("api.jobs.stats", input)
  };

  cron = {
    list: (input: Routes.Cron.ListInput): Promise<Routes.Cron.ListOutput> => this.request("api.cron.list", input)
  };

  ratelimit = {
    check: (input: Routes.Ratelimit.CheckInput): Promise<Routes.Ratelimit.CheckOutput> => this.request("api.ratelimit.check", input),
    reset: (input: Routes.Ratelimit.ResetInput): Promise<Routes.Ratelimit.ResetOutput> => this.request("api.ratelimit.reset", input)
  };

  events = {
    emit: (input: Routes.Events.EmitInput): Promise<Routes.Events.EmitOutput> => this.request("api.events.emit", input)
  };

  sseRoutes = {
    broadcast: (input: Routes.SseRoutes.BroadcastInput): Promise<Routes.SseRoutes.BroadcastOutput> => this.request("api.sseRoutes.broadcast", input),
    clients: (input: Routes.SseRoutes.ClientsInput): Promise<Routes.SseRoutes.ClientsOutput> => this.request("api.sseRoutes.clients", input)
  };
}

/**
 * Create an API client instance
 *
 * @param options.locals - Pass SvelteKit locals for SSR direct calls (no HTTP overhead)
 * @param options.baseUrl - Override the base URL for HTTP calls
 *
 * @example SSR usage in +page.server.ts:
 * ```ts
 * export const load = async ({ locals }) => {
 *   const api = createApi({ locals });
 *   const data = await api.myRoute.get({}); // Direct call, no HTTP!
 *   return { data };
 * };
 * ```
 *
 * @example Browser usage in +page.svelte:
 * ```svelte
 * <script>
 *   import { createApi } from '$lib/api';
 *   const api = createApi(); // HTTP calls
 *   let data = $state(null);
 *   async function load() {
 *     data = await api.myRoute.get({});
 *   }
 * </script>
 * ```
 */
export function createApi(options?: ClientOptions) {
  return new ApiClient(options);
}
