// Auto-generated by scripts/generate-registry.ts
// This file provides type augmentation points for plugins.
// User projects generate their own registry.d.ts via `donkeylabs generate`.

import { type Register, type InferService, type InferSchema, type InferHandlers, type InferMiddleware, type InferDependencies } from "./src/core";

// Plugin Registry - augmented by user projects
declare module "./src/core" {
  export interface PluginRegistry {
    // Plugin types are added here when running `donkeylabs generate`
  }

  export interface PluginHandlerRegistry {
    // Custom handler types are merged here
  }

  export interface PluginMiddlewareRegistry {
    // Custom middleware types are merged here
  }
}

// Union type for all available handlers (base types)
export type AvailableHandlers = "typed" | "raw";

// Union type for all available middleware
export type AvailableMiddleware = never;

// Route builder augmentation for custom handler methods
declare module "./src/router" {
  export interface IRouteBuilder<TRouter> {
    // Custom handler methods are added here
  }

  export interface IMiddlewareBuilder<TRouter> {
    // Custom middleware methods are added here
  }
}
