// Runtime registry - placeholder for user projects
// This file is re-generated by `donkeylabs generate` in user projects
// to register custom handlers and middleware at runtime.
/// <reference path="../registry.d.ts" />
