import { writeFile } from "node:fs/promises";

/**
 * Generate Registry
 *
 * For the library itself, generates empty registry files that serve as templates.
 * User projects run `donkeylabs generate` which uses the CLI to scan their plugins.
 */

async function main() {
  console.log("Generating Plugin Registry (library template)...");

  // Generate registry.d.ts - empty template for library
  const dtsContent = `// Auto-generated by scripts/generate-registry.ts
// This file provides type augmentation points for plugins.
// User projects generate their own registry.d.ts via \`donkeylabs generate\`.

import { type Register, type InferService, type InferSchema, type InferHandlers, type InferMiddleware, type InferDependencies } from "./src/core";

// Plugin Registry - augmented by user projects
declare module "./src/core" {
  export interface PluginRegistry {
    // Plugin types are added here when running \`donkeylabs generate\`
  }

  export interface PluginHandlerRegistry {
    // Custom handler types are merged here
  }

  export interface PluginMiddlewareRegistry {
    // Custom middleware types are merged here
  }
}

// Union type for all available handlers (base types)
export type AvailableHandlers = "typed" | "raw";

// Union type for all available middleware
export type AvailableMiddleware = never;

// Route builder augmentation for custom handler methods
declare module "./src/router" {
  export interface IRouteBuilder<TRouter> {
    // Custom handler methods are added here
  }

  export interface IMiddlewareBuilder<TRouter> {
    // Custom middleware methods are added here
  }
}
`;

  await writeFile("registry.d.ts", dtsContent);
  console.log("Generated registry.d.ts");

  // Generate registry.ts - empty runtime file for library
  const tsContent = `// Auto-generated by scripts/generate-registry.ts
// Runtime registration of custom handler and middleware methods.
// User projects generate their own registry.ts via \`donkeylabs generate\`.
/// <reference path="./registry.d.ts" />
import { RouteBuilder } from "./src/router";

// Handler registrations
// (generated for user projects)

// Middleware registrations
// (generated for user projects - uses Proxy, not prototype extension)
`;

  await writeFile("registry.ts", tsContent);
  console.log("Generated registry.ts");

  console.log("\nLibrary registry template generated.");
  console.log("User projects should run `donkeylabs generate` to create their own registry.");
}

main().catch(console.error);
