// Auto-generated by scripts/generate-registry.ts
// Runtime registration of custom handler and middleware methods.
// User projects generate their own registry.ts via `donkeylabs generate`.
/// <reference path="./registry.d.ts" />
import { RouteBuilder } from "./src/router";

// Handler registrations
// (generated for user projects)

// Middleware registrations
// (generated for user projects - uses Proxy, not prototype extension)
