/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface PasskeyChallenges {
  challenge: string;
  created_at: Generated<string>;
  expires_at: string;
  id: string | null;
  type: string;
  user_id: string | null;
}

export interface Passkeys {
  backed_up: Generated<number>;
  counter: Generated<number>;
  created_at: Generated<string>;
  credential_id: string;
  device_type: string | null;
  id: string | null;
  last_used_at: string | null;
  name: string | null;
  public_key: string;
  transports: string | null;
  user_id: string;
}

export interface RefreshTokens {
  created_at: Generated<string>;
  expires_at: string;
  id: string | null;
  token_hash: string;
  user_id: string;
}

export interface Sessions {
  created_at: Generated<string>;
  expires_at: string;
  id: string | null;
  user_id: string;
}

export interface Users {
  created_at: Generated<string>;
  email: string;
  id: string | null;
  name: string | null;
  password_hash: string;
  updated_at: string;
}

export interface DB {
  passkey_challenges: PasskeyChallenges;
  passkeys: Passkeys;
  refresh_tokens: RefreshTokens;
  sessions: Sessions;
  users: Users;
}
