/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Snapshots {
  counter_name: string;
  created_at: Generated<string | null>;
  id: Generated<number | null>;
  value_at_snapshot: number;
}

export interface DB {
  snapshots: Snapshots;
}
